// flow-typed signature: d6f9b1ce507a082dfd986bff0d6886ac
// flow-typed version: <<STUB>>/todomvc-app-css_v^2.0.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'todomvc-app-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'todomvc-app-css' {
  declare module.exports: any;
}
