export const ADD = 'add'
export const DELETE = 'delete'
export const EDIT = 'edit'
export const COMPLETE = 'complete'
export const COMPLETE_ALL = 'complete_all'
export const CLEAR_COMPLETED = 'clear_completed'